services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    network_mode: host
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

